name = "MyExample"
uuid = "99547a31-48a9-4c63-a493-1333232e307f"
authors = ["wendi gunawan"]
version = "1.0.0-DEV"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
